### ISSUE TITLE
Package Structure

### ISSUE THREAD

**Issue by Norskan** [codemaster3000/MovieManager#10]
add a package prefix to follow the java standard

example
moviemanager.application
moviemanager.database
moviemanager.gui

**Comment by communityFabian** [comment]
still not sure if "Black media manager" is the final name... but we keep it right now as a working title.
Also found the correct term for services like xrel, tmdb -> "scrapers"

(Scraper) (Engl: Kratzer, Schaber): Eine Programm, das Daten aus einer Website oder einem Dokument ausliest (scraping). 

So we could rename some classes with that term (else we have to many _handlers_ ;))

**Comment by Norskan** [comment]
okay renaming into scrapers is probably not the worst idea

**Comment by Norskan** [comment]
solved in https://github.com/codemaster3000/MovieManager/pull/20
