### ISSUE TITLE
Buildserver

### ISSUE THREAD

**Issue by Norskan** [codemaster3000/MovieManager#12]
Now that we have maven. Should we use a continous integration server?

**Comment by communityFabian** [comment]
would be a nice addition. Jenkins ? i added a build pass sign to the github readme so there we can see if the builds are successfull

**Comment by Norskan** [comment]
yea we could use jenkins or trevis!

**Comment by Norskan** [comment]
i will add trevis to becaus it also checks pull requests

**Comment by Norskan** [comment]
travis is integrated. still debation if we use jenkins as well
