### ISSUE TITLE
Splite up Monolith?

### ISSUE THREAD

**Issue by Norskan** [codemaster3000/MovieManager#19]
introduce an application layer that is used by a rest service
rest service is then used by a web frontent or desktop client

would probably make managing the db simpler in long term

**Comment by communityFabian** [comment]
as we need later a webinterface (read only) such a service may be usefull
(JAX api ?)

**Comment by Norskan** [comment]
yea something simple and strait forware!

**Comment by Norskan** [comment]
https://jersey.java.net/ would be a nice alternative if we want to avoid glassfish

**Comment by communityFabian** [comment]
ok sounds good

**Comment by communityFabian** [comment]
We can integrate this for milestone#2
