### ISSUE TITLE
fxml "fitParent" resize fail

### ISSUE THREAD

**Issue by communityFabian** [codemaster3000/MovieManager#8]
automatisches resize funktioniert nicht mehr in der GUI. Vermutung: Parent objekt problem im fxmloader

**Comment by Norskan** [comment]
was heist nicht mehr funktionerieren genau! beispiel währe fein damit man das ganze ausprobieren könnte

**Comment by Norskan** [comment]
Liegt warscheinlich an den zeilen 23 bis 26 in main.java

**Comment by Norskan** [comment]
okay i kann jetzt bestätigen das da bug des vermutete war! i wir des fixen und den amol in nam bugfix branch pushen

**Comment by communityFabian** [comment]
issued solved, ready for dev merge
